##################
# code/submission/nonpareil3_run.sub
# Submission script for calculating
# metagenome coverage and diversity.

# Benjamin D. Peterson
##################

request_cpus = 10
request_memory = 30GB

executable = /home/GLBRCORG/bpeterson26/Everglades/code/executables/nonpareil3_run.sh

environment = "metagenome=$(metagenome) \
              workingDirectory=/home/GLBRCORG/bpeterson26/Everglades/dataEdited/2019_readBasedAnalysis/nonpareil \
              metagenomeFolder=/home/GLBRCORG/bpeterson26/Everglades/dataEdited/metagenomes"

output = /home/GLBRCORG/bpeterson26/Everglades/reports/outs/$(metagenome)_nonpareil3.out
error = /home/GLBRCORG/bpeterson26/Everglades/reports/errs/$(metagenome)_nonpareil3.err
log = /home/GLBRCORG/bpeterson26/Everglades/reports/logs/$(metagenome)_nonpareil3.log

queue metagenome from /home/GLBRCORG/bpeterson26/Everglades/metadata/lists/2019_analysis_assembly_metagenomes_list.txt
